

CROSS-VALIDATION-TEST/5cv.txt:
	mkdir -p CROSS-VALIDATION-TEST
	../../../bin/trainTest --pathway braf-data/pathway.tab --set1 braf-data/obs.tab --set2 ras-data/obs.tab --output CROSS-VALIDATION-TEST --libdaiBIN ../../../bin/runEM_BP:../../../bin/runINFERENCES --no_shared_em 

clean:
	rm -rf CROSS-VALIDATION-TEST


