

2cv.txt:
	../../../bin/2CVtest --pathway braf-data/pathway.tab --set1 braf-data/obs.tab --set2 ras-data/obs.tab --output brafTrain_rasTest --libdaiBIN ../../../bin/runEM_BP:../../../bin/runINFERENCES --no_shared_em > $@
